[server]
host = "0.0.0.0"
port = 443

[tls]
enabled = true
cert_dir = "cert"
country = "VN"
organization = "test"
common_name = "localhost"
sans = []

[redis]
enabled = true
url = "redis://127.0.0.1/"

